apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulse.secretName" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  influxdb-token: {{ .Values.influxdb.adminToken | quote }}
  grafana-admin-user: {{ .Values.grafana.adminUser | quote }}
  grafana-admin-password: {{ .Values.grafana.adminPassword | quote }}
