resource "local_sensitive_file" "connection_string" {
  count = var.write_local_credentials ? 1 : 0

  content         = azurerm_storage_account.archive.primary_connection_string
  filename        = "${local.credentials_dir}/azure-archive-connection-string"
  file_permission = "0600"
}

resource "local_file" "env_local_snippet" {
  count = var.write_local_credentials ? 1 : 0

  content = <<-EOT
    # Streamclone archive — generated by deploy/terraform/azure/archive (terraform apply)
    # Merge into .env.local (keep ARCHIVE_ENABLED=false until internal/archive.Writer ships)
    ARCHIVE_ENABLED=false
    ARCHIVE_STORAGE_PROVIDER=azure
    ARCHIVE_AZURE_STORAGE_ACCOUNT=${azurerm_storage_account.archive.name}
    ARCHIVE_AZURE_CONTAINER=${azurerm_storage_container.archive.name}
    ARCHIVE_AZURE_PREFIX=${var.archive_prefix}
    ARCHIVE_AZURE_CONNECTION_STRING_FILE=${var.env_local_connection_string_path}
    ARCHIVE_EXPORT_ON_SYNC=false
    ARCHIVE_PROTECT_RETENTION=false
  EOT

  filename        = "${local.credentials_dir}/archive.env.local.snippet"
  file_permission = "0600"
}

resource "local_file" "setup_readme" {
  count = var.write_local_credentials ? 1 : 0

  content = <<-EOT
    Streamclone Azure archive — provisioned by Terraform

    Storage account : ${azurerm_storage_account.archive.name}
    Container       : ${azurerm_storage_container.archive.name}
    Blob prefix     : ${var.archive_prefix}
    Resource group  : ${azurerm_resource_group.archive.name}

    Credentials     : ${local.credentials_dir}/azure-archive-connection-string
    Env snippet     : ${local.credentials_dir}/archive.env.local.snippet

    Next:
      1. Copy archive.env.local.snippet into repo .env.local
      2. Implement internal/archive.Writer (Azure Blob backend)
      3. Set ARCHIVE_ENABLED=true when Writer is ready

    Docs: docs/azure-archive-setup.md · docs/finalplan.md · docs/scraping-archive/requirements.md
  EOT

  filename        = "${local.credentials_dir}/archive-setup.txt"
  file_permission = "0644"
}
