output "resource_group_name" {
  description = "Azure resource group name."
  value       = azurerm_resource_group.archive.name
}

output "location" {
  description = "Azure region."
  value       = azurerm_resource_group.archive.location
}

output "storage_account_name" {
  description = "Set ARCHIVE_AZURE_STORAGE_ACCOUNT to this value."
  value       = azurerm_storage_account.archive.name
}

output "container_name" {
  description = "Set ARCHIVE_AZURE_CONTAINER to this value."
  value       = azurerm_storage_container.archive.name
}

output "archive_prefix" {
  description = "Set ARCHIVE_AZURE_PREFIX to this value."
  value       = var.archive_prefix
}

output "blob_endpoint" {
  description = "Primary blob endpoint for the storage account."
  value       = azurerm_storage_account.archive.primary_blob_endpoint
}

output "smoke_blob_url" {
  description = "HTTPS URL of the Terraform smoke-test blob."
  value       = "${azurerm_storage_account.archive.primary_blob_endpoint}${azurerm_storage_container.archive.name}/${local.smoke_blob_name}"
}

output "credentials_dir" {
  description = "Local directory where Terraform wrote credentials (when write_local_credentials=true)."
  value       = local.credentials_dir
}

output "connection_string_file" {
  description = "Path to generated connection string file."
  value       = var.write_local_credentials ? local_sensitive_file.connection_string[0].filename : null
}

output "env_local_snippet_file" {
  description = "Path to generated .env.local snippet."
  value       = var.write_local_credentials ? local_file.env_local_snippet[0].filename : null
}

output "env_local_snippet" {
  description = "Copy into .env.local (also written to credentials dir when write_local_credentials=true)."
  value       = <<-EOT
    # Streamclone archive — generated by deploy/terraform/azure/archive
    ARCHIVE_ENABLED=false
    ARCHIVE_STORAGE_PROVIDER=azure
    ARCHIVE_AZURE_STORAGE_ACCOUNT=${azurerm_storage_account.archive.name}
    ARCHIVE_AZURE_CONTAINER=${azurerm_storage_container.archive.name}
    ARCHIVE_AZURE_PREFIX=${var.archive_prefix}
    ARCHIVE_AZURE_CONNECTION_STRING_FILE=${var.env_local_connection_string_path}
    ARCHIVE_EXPORT_ON_SYNC=false
    ARCHIVE_PROTECT_RETENTION=false
  EOT
}

output "setup_summary" {
  description = "Human-readable post-apply summary."
  value       = <<-EOT
    Streamclone Azure archive is ready.

    Storage account : ${azurerm_storage_account.archive.name}
    Container       : ${azurerm_storage_container.archive.name}
    Prefix          : ${var.archive_prefix}
    Resource group  : ${azurerm_resource_group.archive.name}

    Generated files (${local.credentials_dir}):
      - azure-archive-connection-string
      - archive.env.local.snippet  → merge into .env.local
      - archive-setup.txt

    Next: implement internal/archive.Writer, then set ARCHIVE_ENABLED=true.
    Track progress: docs/scraping-archive/requirements.md (Phase 1)
    Architecture:   docs/finalplan.md (Phase A)
  EOT
}

output "primary_connection_string" {
  description = "Storage account connection string. Also written to credentials dir. Never commit."
  value       = azurerm_storage_account.archive.primary_connection_string
  sensitive   = true
}

output "remote_state_hint" {
  description = "Optional: migrate local state to Azure after first apply."
  value       = var.create_tfstate_container ? "terraform init -migrate-state -backend-config=storage_account_name=${azurerm_storage_account.archive.name} -backend-config=container_name=${var.tfstate_container_name} -backend-config=key=archive.tfstate" : null
}
